# Generated by Django 4.0.4 on 2022-07-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex_color',
            new_name='color',
        ),
    ]
